coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false
